#pragma once
#include <M5Unified.h>

typedef struct key_input
{
  std::string text;
  uint8_t keycode;
  uint8_t modifier;
} key_input_t;

static const key_input_t KEY_a = {"a", 0x04, 0};
static const key_input_t KEY_A = {"A", 0x04, 1};
static const key_input_t KEY_b = {"b", 0x05, 0};
static const key_input_t KEY_B = {"B", 0x05, 1};
static const key_input_t KEY_c = {"c", 0x06, 0};
static const key_input_t KEY_C = {"C", 0x06, 1};
static const key_input_t KEY_d = {"d", 0x07, 0};
static const key_input_t KEY_D = {"D", 0x07, 1};
static const key_input_t KEY_e = {"e", 0x08, 0};
static const key_input_t KEY_E = {"E", 0x08, 1};
static const key_input_t KEY_f = {"f", 0x09, 0};
static const key_input_t KEY_F = {"F", 0x09, 1};
static const key_input_t KEY_g = {"g", 0x0a, 0};
static const key_input_t KEY_G = {"G", 0x0a, 1};
static const key_input_t KEY_h = {"h", 0x0b, 0};
static const key_input_t KEY_H = {"H", 0x0b, 1};
static const key_input_t KEY_i = {"i", 0x0c, 0};
static const key_input_t KEY_I = {"I", 0x0c, 1};
static const key_input_t KEY_j = {"j", 0x0d, 0};
static const key_input_t KEY_J = {"J", 0x0d, 1};
static const key_input_t KEY_k = {"k", 0x0e, 0};
static const key_input_t KEY_K = {"K", 0x0e, 1};
static const key_input_t KEY_l = {"l", 0x0f, 0};
static const key_input_t KEY_L = {"L", 0x0f, 1};
static const key_input_t KEY_m = {"m", 0x10, 0};
static const key_input_t KEY_M = {"M", 0x10, 1};
static const key_input_t KEY_n = {"n", 0x11, 0};
static const key_input_t KEY_N = {"N", 0x11, 1};
static const key_input_t KEY_o = {"o", 0x12, 0};
static const key_input_t KEY_O = {"O", 0x12, 1};
static const key_input_t KEY_p = {"p", 0x13, 0};
static const key_input_t KEY_P = {"P", 0x13, 1};
static const key_input_t KEY_q = {"q", 0x14, 0};
static const key_input_t KEY_Q = {"Q", 0x14, 1};
static const key_input_t KEY_r = {"r", 0x15, 0};
static const key_input_t KEY_R = {"R", 0x15, 1};
static const key_input_t KEY_s = {"s", 0x16, 0};
static const key_input_t KEY_S = {"S", 0x16, 1};
static const key_input_t KEY_t = {"t", 0x17, 0};
static const key_input_t KEY_T = {"T", 0x17, 1};
static const key_input_t KEY_u = {"u", 0x18, 0};
static const key_input_t KEY_U = {"U", 0x18, 1};
static const key_input_t KEY_v = {"v", 0x19, 0};
static const key_input_t KEY_V = {"V", 0x19, 1};
static const key_input_t KEY_w = {"w", 0x1a, 0};
static const key_input_t KEY_W = {"W", 0x1a, 1};
static const key_input_t KEY_x = {"x", 0x1b, 0};
static const key_input_t KEY_X = {"X", 0x1b, 1};
static const key_input_t KEY_y = {"y", 0x1c, 0};
static const key_input_t KEY_Y = {"Y", 0x1c, 1};
static const key_input_t KEY_z = {"z", 0x1d, 0};
static const key_input_t KEY_Z = {"Z", 0x1d, 1};

static const key_input_t KEY_1 = {"1", 0x1e, 0};
static const key_input_t KEY_exclamation_mark = {"!", 0x1e, 1};
static const key_input_t KEY_2 = {"2", 0x1f, 0};
static const key_input_t KEY_atmark = {"@", 0x1f, 1};
static const key_input_t KEY_3 = {"3", 0x20, 0};
static const key_input_t KEY_number_sign = {"#", 0x20, 1};
static const key_input_t KEY_4 = {"4", 0x21, 0};
static const key_input_t KEY_doller = {"$", 0x21, 1};
static const key_input_t KEY_5 = {"5", 0x22, 0};
static const key_input_t KEY_percent = {"%", 0x22, 1};
static const key_input_t KEY_6 = {"6", 0x23, 0};
static const key_input_t KEY_caret = {"^", 0x23, 1};
static const key_input_t KEY_7 = {"7", 0x24, 0};
static const key_input_t KEY_ampersand = {"&", 0x24, 1};
static const key_input_t KEY_8 = {"8", 0x25, 0};
static const key_input_t KEY_asterisk = {"*", 0x25, 1};
static const key_input_t KEY_9 = {"9", 0x26, 0};
static const key_input_t KEY_left_parenthesis = {"(", 0x26, 1};
static const key_input_t KEY_0 = {"0", 0x27, 0};
static const key_input_t KEY_right_parenthesis = {")", 0x27, 1};

static const key_input_t KEY_ENTER = {"ENTER", 0x28, 0};
static const key_input_t KEY_ESCAPE = {"ESCAPE", 0x29, 0};
static const key_input_t KEY_Backspace = {"Backspace", 0x2a, 0};
static const key_input_t KEY_Tab = {"Tab", 0x2b, 0};
static const key_input_t KEY_Spacebar = {"Spacebar", 0x2c, 0};

static const key_input_t KEY_hyphen = {"-", 0x2d, 0};
static const key_input_t KEY_underscore = {"_", 0x2d, 1};
static const key_input_t KEY_equal = {"=", 0x2e, 0};
static const key_input_t KEY_plus = {"+", 0x2e, 1};
static const key_input_t KEY_left_square_bracket = {"[", 0x2f, 0};
static const key_input_t KEY_left_curly_bracket = {"{", 0x2f, 1};
static const key_input_t KEY_right_square_bracket = {"]", 0x30, 0};
static const key_input_t KEY_right_curly_bracket = {"}", 0x30, 1};
static const key_input_t KEY_backslash = {"\\", 0x31, 0};
static const key_input_t KEY_tilda = {"~", 0x32, 0};
static const key_input_t KEY_semicolon = {";", 0x33, 0};
static const key_input_t KEY_quote = {"'", 0x34, 0};
static const key_input_t KEY_double_quote = {"\"", 0x34, 1};
static const key_input_t KEY_backquote = {"`", 0x35, 0};
static const key_input_t KEY_comma = {",", 0x36, 0};
static const key_input_t KEY_period = {".", 0x37, 0};
static const key_input_t KEY_slash = {"/", 0x38, 0};
static const key_input_t KEY_question = {"?", 0x38, 1};

static const key_input_t KEY_CapsLock = {"Caps Lock", 0x39, 0};
static const key_input_t KEY_F1 = {"F1", 0x3a, 0};
static const key_input_t KEY_F2 = {"F2", 0x3b, 0};
static const key_input_t KEY_F3 = {"F3", 0x3c, 0};
static const key_input_t KEY_F4 = {"F4", 0x3d, 0};
static const key_input_t KEY_F5 = {"F5", 0x3e, 0};
static const key_input_t KEY_F6 = {"F6", 0x3f, 0};
static const key_input_t KEY_F7 = {"F7", 0x40, 0};
static const key_input_t KEY_F8 = {"F8", 0x41, 0};
static const key_input_t KEY_F9 = {"F9", 0x42, 0};
static const key_input_t KEY_F10 = {"F10", 0x43, 0};
static const key_input_t KEY_F11 = {"F11", 0x44, 0};
static const key_input_t KEY_F12 = {"F12", 0x45, 0};
static const key_input_t KEY_PrintScreen = {"PrintScreen", 0x46, 0};
static const key_input_t KEY_ScrollLock = {"Scroll Lock", 0x47, 0};
static const key_input_t KEY_Pause = {"Pause", 0x48, 0};
static const key_input_t KEY_Insert = {"Insert", 0x49, 0};
static const key_input_t KEY_Home = {"Home", 0x4a, 0};
static const key_input_t KEY_PageUp = {"PageUp", 0x4b, 0};
static const key_input_t KEY_DeleteForward = {"Delete Forward", 0x4c, 0};
static const key_input_t KEY_End = {"End", 0x4d, 0};
static const key_input_t KEY_PageDown = {"PageDown", 0x4e, 0};
static const key_input_t KEY_RightArrow = {"RightArrow", 0x4f, 0};
static const key_input_t KEY_LeftArrow = {"LeftArrow", 0x50, 0};
static const key_input_t KEY_DownArrow = {"DownArrow", 0x51, 0};
static const key_input_t KEY_UpArrow = {"UpArrow", 0x52, 0};
